# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'achievements.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pymongo import MongoClient
from settings import sum_parameter

root = MongoClient("localhost", 27017)
activity_adder_db = root['activity_adder_db']
settings = activity_adder_db['settings']
user_activities = activity_adder_db['user_activities']


class Ui_Achievements(object):
    def setupUi(self, Achievements, MainWindow):
        self.achievements = Achievements
        self.main_window = MainWindow

        Achievements.setObjectName("MainWindow")
        Achievements.resize(800, 643)

        self.centralwidget = QtWidgets.QWidget(Achievements)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 776, 533))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout_scroll_area = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_scroll_area.setObjectName("verticalLayout_2")

        for elem, i in zip(settings.find({}), range(settings.count_documents({}))):
            activity = elem['activity']
            for j, param in enumerate(["duration", "distance"]):
                current_goal = elem['objective_' + str(param)]
                current_value = sum(sum_parameter(param, activity, user_activities))
                label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
                label.setGeometry(QtCore.QRect(10, 40 + 80 * (2 * i + j), 221, 16))
                label.setText(f"{activity} {param} {current_value}/{current_goal}")
                self.verticalLayout_scroll_area.addWidget(label)
                progress_bar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
                progress_bar.setGeometry(QtCore.QRect(10, 80 + 80 * (2 * i + j), 751, 23))
                progress_bar.setProperty("value", (current_value / current_goal) * 100)
                self.verticalLayout_scroll_area.addWidget(progress_bar)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setObjectName("cancel_button")

        self.verticalLayout.addWidget(self.cancel_button)
        Achievements.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(Achievements)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Achievements.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(Achievements)
        self.statusbar.setObjectName("statusbar")
        Achievements.setStatusBar(self.statusbar)

        self.retranslateUi(Achievements)
        QtCore.QMetaObject.connectSlotsByName(Achievements)

        self.cancel_button.clicked.connect(self.to_main_menu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancel_button.setText(_translate("MainWindow", "Back to menu"))

    def to_main_menu(self):
        self.achievements.close()
        self.main_window.show()
