# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activity_adder.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActivityAdder(object):
    def setupUi(self, ActivityAdder):
        ActivityAdder.setObjectName("ActivityAdder")
        ActivityAdder.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(ActivityAdder)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 680, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 680, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(200, 0, 392, 236))
        self.calendarWidget.setObjectName("calendarWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 520, 351, 91))
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(490, 390, 42, 22))
        self.spinBox.setMaximum(300)
        self.spinBox.setObjectName("spinBox")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(470, 300, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 300, 171, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 390, 171, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 480, 171, 20))
        self.label_3.setObjectName("label_3")
        ActivityAdder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ActivityAdder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ActivityAdder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ActivityAdder)
        self.statusbar.setObjectName("statusbar")
        ActivityAdder.setStatusBar(self.statusbar)

        self.retranslateUi(ActivityAdder)
        QtCore.QMetaObject.connectSlotsByName(ActivityAdder)

    def retranslateUi(self, ActivityAdder):
        _translate = QtCore.QCoreApplication.translate
        ActivityAdder.setWindowTitle(_translate("ActivityAdder", "MainWindow"))
        self.pushButton.setText(_translate("ActivityAdder", "PushButton"))
        self.pushButton_2.setText(_translate("ActivityAdder", "PushButton"))
        self.comboBox.setItemText(0, _translate("ActivityAdder", "Running"))
        self.comboBox.setItemText(1, _translate("ActivityAdder", "Swimming"))
        self.comboBox.setItemText(2, _translate("ActivityAdder", "Cycling"))
        self.comboBox.setItemText(3, _translate("ActivityAdder", "Stretching"))
        self.label.setText(_translate("ActivityAdder", "What was your daily activity?"))
        self.label_2.setText(_translate("ActivityAdder", "What was a duration?"))
        self.label_3.setText(_translate("ActivityAdder", "Summary"))
