# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from pymongo import MongoClient
root = MongoClient("localhost", 27017)
activity_adder_db = root['activity_adder_db']
settings = activity_adder_db['settings']


class Ui_SettingsManager(object):
    def setupUi(self, SettingsManager, MainWindow):
        self.settings_manager = SettingsManager
        self.main_window = MainWindow

        SettingsManager.setObjectName("SettingsManager")
        SettingsManager.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SettingsManager)
        self.centralwidget.setObjectName("centralwidget")

        self.add_new_activity = QtWidgets.QLineEdit(self.centralwidget)
        self.add_new_activity.setGeometry(QtCore.QRect(440, 160, 113, 22))
        self.add_new_activity.setObjectName("add_new_activity")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 160, 131, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 220, 131, 20))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.change_language_box = QtWidgets.QComboBox(self.centralwidget)
        self.change_language_box.setGeometry(QtCore.QRect(460, 220, 73, 22))
        self.change_language_box.setObjectName("change_language_box")
        self.change_language_box.addItem("")
        self.change_language_box.addItem("")
        self.change_language_box.addItem("")

        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(680, 500, 93, 28))
        self.save_button.setObjectName("save_button")

        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(20, 500, 93, 28))
        self.cancel_button.setObjectName("cancel_button")

        SettingsManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        SettingsManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsManager)
        self.statusbar.setObjectName("statusbar")
        SettingsManager.setStatusBar(self.statusbar)

        self.retranslateUi(SettingsManager)
        QtCore.QMetaObject.connectSlotsByName(SettingsManager)

        self.cancel_button.clicked.connect(self.to_main_menu)
        self.save_button.clicked.connect(self.save)

    def retranslateUi(self, SettingsManager):
        _translate = QtCore.QCoreApplication.translate
        SettingsManager.setWindowTitle(_translate("SettingsManager", "MainWindow"))
        self.label.setText(_translate("SettingsManager", "Add activity"))
        self.label_2.setText(_translate("SettingsManager", "Change language"))
        self.change_language_box.setItemText(0, _translate("SettingsManager", "ENG"))
        self.change_language_box.setItemText(1, _translate("SettingsManager", "PL"))
        self.change_language_box.setItemText(2, _translate("SettingsManager", "DE"))
        self.save_button.setText(_translate("SettingsManager", "Save"))
        self.cancel_button.setText(_translate("SettingsManager", "Cancel"))

    def to_main_menu(self):
        self.settings_manager.close()
        self.main_window.show()

    def save(self):
        new_settings = {
            "activity": self.add_new_activity.text()
        }
        settings.insert_one(new_settings)
        self.to_main_menu()